# Generated by Django 5.1.1 on 2024-10-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('quiz', 'Quiz')], default='type1', max_length=255),
        ),
    ]
