# Generated by Django 5.1.1 on 2024-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_node_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
