# Generated by Django 5.1.1 on 2024-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_profilenode_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exoplanets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_name', models.CharField(max_length=29)),
                ('hostname', models.CharField(max_length=27)),
                ('sy_snum', models.CharField(max_length=7)),
                ('sy_pnum', models.CharField(max_length=7)),
                ('discoverymethod', models.CharField(max_length=29)),
                ('disc_year', models.CharField(max_length=9)),
                ('disc_facility', models.CharField(max_length=46)),
                ('pl_rade', models.CharField(blank=True, max_length=7, null=True)),
                ('pl_radj', models.CharField(blank=True, max_length=7, null=True)),
                ('pl_bmasse', models.CharField(blank=True, max_length=11, null=True)),
                ('st_spectype', models.CharField(blank=True, max_length=16, null=True)),
                ('st_teff', models.CharField(blank=True, max_length=8, null=True)),
                ('st_rad', models.CharField(blank=True, max_length=6, null=True)),
                ('st_mass', models.CharField(blank=True, max_length=7, null=True)),
                ('st_met', models.CharField(blank=True, max_length=6, null=True)),
                ('st_metratio', models.CharField(blank=True, max_length=11, null=True)),
                ('rastr', models.CharField(max_length=14)),
                ('ra', models.CharField(max_length=11)),
                ('sy_dist', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
